#!/usr/bin/env bash

git clone https://github.com/jhessin/dvp.git ~/Documents/dvp

echo "alias dvp=\"cd ~/Documents/dvp\"" >> ~/.bashrc
alias dvp="cd ~/Documents/dvp"

cd ~/Documents/dvp
./install.sh
