#!/usr/bin/env bash

git clone https://github.com/jhessin/dvp.git ~/Documents/dvp

cd ~/Documents/dvp
./install.sh

echo "alias dvp=\"cd ~/Documents/dvp\"" >> ~/.bashrc
alias dvp="cd ~/Documents/dvp"
